### ISSUE TITLE
Images are squishing in markdown

### ISSUE THREAD

**Issue by colordepth** [CSE-333-Computer-Graphics-2022/Image-Morphing#4]
:)

**Comment by Ambujbhaskar** [comment]
Fixed Banner gif and result image sequence repsonsiveness.

**Comment by KaranMano** [comment]
@colordepth Main now has the required changes

**Comment by colordepth** [comment]
Thank u for the speedy resolution. My organization's workflow was being affected by this bug. Glad it got fixed 🙂. Now I'll go make some CPUs using the silicon that I mined from the rocks in my backyard.

**Comment by colordepth** [comment]
@KaranMano @Ambujbhaskar do you have some quartz or mica around your home that I can borrow?

**Comment by colordepth** [comment]
@KaranMano The issue persists in other images in the markdown 😞

![Screenshot_2025-01-19-03-24-34-36_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/4f9d6ead-2e46-45b2-9ab3-b06c067a8ac2)
